#!/bin/sh
set -e

detect_base() {
    current=$(git branch --show-current)
    branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
    best=""
    best_count=9999999999999999 # large number you should not be that ahead on 

    for b in $branches; do
	    [ "$b" = "$current" ] && continue
	    count=$(git rev-list --count "$b..$current")
	    if [ "$count" -lt "$best_count" ]; then
		    best="$b"
		    best_count="$count"
	    fi
    done

    echo "$best"
}

if [ "$1" = "quick" ] || [ "$1" = "q" ]; then
    message="$2"
    shift 2

    new_branch="quick/$(date +%Y%m%d%H%M%S)"
    git checkout -b "$new_branch"
    git add -A
    git commit -m "$message"
fi

base=$(detect_base)
if [ -n "$base" ]; then
    echo "Stack base: $base"
    exec gh pr create -B "$base" "$@"
else
    exec gh pr create "$@"
fi

